apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: tori-app
type: Opaque
stringData:
  # MySQL Member DB
  MYSQL_MEMBER_USER: "member_user"
  MYSQL_MEMBER_PASSWORD: "member_pass"
  MYSQL_MEMBER_ROOT_PASSWORD: "rootpass"
  # MySQL Product DB
  MYSQL_PRODUCT_USER: "product_user"
  MYSQL_PRODUCT_PASSWORD: "product_pass"
  MYSQL_PRODUCT_ROOT_PASSWORD: "rootpass"
  # MySQL Order DB
  MYSQL_ORDER_USER: "order_user"
  MYSQL_ORDER_PASSWORD: "order_pass"
  MYSQL_ORDER_ROOT_PASSWORD: "rootpass"
  # MySQL Inventory DB
  MYSQL_INVENTORY_USER: "inventory_user"
  MYSQL_INVENTORY_PASSWORD: "inventory_pass"
  MYSQL_INVENTORY_ROOT_PASSWORD: "rootpass"
  # RabbitMQ
  RABBITMQ_USER: "guest"
  RABBITMQ_PASSWORD: "guest"
  # JWT
  JWT_SECRET: "your-256-bit-secret-key-here-must-be-at-least-32-characters-long"
---
apiVersion: v1
kind: Secret
metadata:
  name: mail-secrets
  namespace: tori-app
type: Opaque
stringData:
  MAIL_USERNAME: "your-mail@gmail.com"
  MAIL_PASSWORD: "your-app-password"